---
- name: "ensure vim installed"
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - vim
  when: ansible_os_family == "Debian"

- name: "ensure vim config is present"
  copy: 
    src: vimrc
    dest: ~/.vimrc

